import { Injectable } from '@angular/core';
import { MerchantService } from '@core/services';
import { of, Observable } from 'rxjs';
export const MockMerchantList = [
    {
        merchant_id: 100864,
        merchant_biz_name: 'Merchant Test 15',
        merchant_code: 'MC100864',
        merchant_name: 'Merchant Test 15',
        is_master_merchant: 0,
        master_id: null,
        master_name: null,
        agent_phone: '0943222111',
        agent_email: 'qcalbawvc@emltmp.com',
        agent_identity: '323443243',
        agent_name: 'Huyền',
        company_type: 'CTCP',
        business_type: 4899,
        business_type_name: 'Cable and other pay television (previously Cable Services)',
        tax_code: null,
        address: 'HN',
        created_date: '01/07/2020',
        website: null,
        creator_id: 24,
        creator_user: 'HuyenPTT',
        creator_via: 'MM',
        status: 'active',
        status_name: 'Active',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/4A817B1603B0BB00B6556EC207710E72-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/846C260D715E5B854FFAD5F70A516C88-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/846C260D715E5B854FFAD5F70A516C88-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/4A817B1603B0BB00B6556EC207710E72.jpg',
            agency_id: 100010,
            agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
        ],
        province: {
            id: '08',
            name: 'Tỉnh Tuyên Quang',
        },
        district: {
            id: '073',
            name: 'Huyện Chiêm Hóa',
        },
        commune: {
            id: '02305',
            name: 'Xã Trung Hà',
        },
        desc: 'a'
    },
    {
        merchant_id: 100863,
        merchant_biz_name: 'Merchant Test 14',
        merchant_code: 'MC100863',
        merchant_name: 'Merchant Test 14',
        is_master_merchant: 0,
        master_id: null,
        master_name: null,
        agent_phone: '0912332444',
        agent_email: 'rizkrimg@firste.ml',
        agent_identity: '123433221',
        agent_name: 'Huyền',
        company_type: 'HKDCT',
        business_type: 4899,
        business_type_name: 'Cable and other pay television (previously Cable Services)',
        tax_code: null,
        address: 'HN',
        created_date: '01/07/2020',
        website: null,
        creator_id: 24,
        creator_user: 'HuyenPTT',
        creator_via: 'MM',
        status: 'active',
        status_name: 'Active',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/7DDA218CE80CDFC6FF2C76E0E8E6298E-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/DC5689792E08EB2E219DCE49E64C885B-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/DC5689792E08EB2E219DCE49E64C885B-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/7DDA218CE80CDFC6FF2C76E0E8E6298E.jpg',
            agency_id: 100010,
            agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
        ],
        province: {
            id: '08',
            name: 'Tỉnh Tuyên Quang',
        },
        district: {
            id: '073',
            name: 'Huyện Chiêm Hóa',
        },
        commune: {
            id: '02305',
            name: 'Xã Trung Hà',
        },
        desc: 'a'
    },
    {
        merchant_id: 100852,
        merchant_biz_name: 'Merchant Test 13',
        merchant_code: 'MC100852',
        merchant_name: 'Merchant Test 13',
        is_master_merchant: 1,
        master_id: null,
        master_name: null,
        agent_phone: '0987654347',
        agent_email: 'yjlfhyikfamz@dropmail.me',
        agent_identity: '589765891',
        agent_name: 'Huyền',
        company_type: 'TNHH',
        business_type: 4829,
        business_type_name: 'Money Orders - Wire Transfer',
        tax_code: null,
        address: 'HN',
        created_date: '30/06/2020',
        website: null,
        creator_id: 24,
        creator_user: 'HuyenPTT',
        creator_via: 'MM',
        status: 'active',
        status_name: 'Active',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/0152BA0B3C75F77D77EA3FA98E33CD3B-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/2DACE78F80BC92E6D7493423D729448E-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/2DACE78F80BC92E6D7493423D729448E-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/0152BA0B3C75F77D77EA3FA98E33CD3B.jpg',
            agency_id: 100010,
            agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
        ],
        province: {
            id: '04',
            name: 'Tỉnh Cao Bằng',
        },
        district: {
            id: '045',
            name: 'Huyện Hà Quảng',
        },
        commune: {
            id: '01399',
            name: 'Xã Trường Hà',
        },desc: 'a'
    },
    {
        merchant_id: 100849,
        merchant_biz_name: 'Việt Á',
        merchant_code: 'MC100849',
        merchant_name: 'Công ty nhựa Việt Á',
        is_master_merchant: 1,
        master_id: null,
        master_name: null,
        agent_phone: '0367977088',
        agent_email: 'yjmxlojnbpca@dropmail.me',
        agent_identity: '017133958',
        agent_name: 'Nguyễn Văn A',
        company_type: 'CTLD',
        business_type: 4821,
        business_type_name: 'Telegraph services',
        tax_code: null,
        address: 'Địa chỉ',
        created_date: '30/06/2020',
        website: null,
        creator_id: 272,
        creator_user: 'Nguyễn Văn A',
        creator_via: 'MM',
        status: 'active',
        status_name: 'Active',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/2D3B08D8ECE73A9EDD41096203ED1EA1-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/C15DA1F2B5E5ED6E6837A3802F0D1593-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/C15DA1F2B5E5ED6E6837A3802F0D1593-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/2D3B08D8ECE73A9EDD41096203ED1EA1.jpg',
            agency_id: 100021,
            agency_name: 'Đại lý 1111111111111111111111111111111111111111111',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
            {
                method_id: 101,
                activated: 1,
            },
        ],
        province: {
            id: '10',
            name: 'Tỉnh Lào Cai',
        },
        district: {
            id: '085',
            name: 'Huyện Bắc Hà',
        },
        commune: {
            id: '02839',
            name: 'Thị trấn Bắc Hà',
        },desc: 'a'
    },
    {
        merchant_id: 100848,
        merchant_biz_name: 'Merchant Test 12',
        merchant_code: 'MC100848',
        merchant_name: 'Merchant Test 12',
        is_master_merchant: 0,
        master_id: null,
        master_name: null,
        agent_phone: '0943222111',
        agent_email: 'tvdfrfab@netmail.tk',
        agent_identity: '323443243',
        agent_name: 'Huyền',
        company_type: 'CTCP',
        business_type: 4899,
        business_type_name: 'Cable and other pay television (previously Cable Services)',
        tax_code: null,
        address: 'HN',
        created_date: '30/06/2020',
        website: null,
        creator_id: 24,
        creator_user: 'HuyenPTT',
        creator_via: 'MM',
        status: 'active',
        status_name: 'Active',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/8AD06C1237D7AC29AF2BC0071D55F80D-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/3621F1454CACF995530EA53652DDF8FB-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/3621F1454CACF995530EA53652DDF8FB-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/8AD06C1237D7AC29AF2BC0071D55F80D.jpg',
            agency_id: 100010,
            agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
        ],
        province: {
            id: '08',
            name: 'Tỉnh Tuyên Quang',
        },
        district: {
            id: '073',
            name: 'Huyện Chiêm Hóa',
        },
        commune: {
            id: '02305',
            name: 'Xã Trung Hà',
        },desc: 'a'
    },
    {
        merchant_id: 100847,
        merchant_biz_name: 'Merchant Test 11',
        merchant_code: 'MC100847',
        merchant_name: 'Merchant Test 11',
        is_master_merchant: 0,
        master_id: null,
        master_name: null,
        agent_phone: '0912444566',
        agent_email: 'zoygqulg@firste.ml',
        agent_identity: '112111111',
        agent_name: 'Huyền',
        company_type: 'DNTN',
        business_type: 4829,
        business_type_name: 'Money Orders - Wire Transfer',
        tax_code: null,
        address: 'HN',
        created_date: '30/06/2020',
        website: null,
        creator_id: 282,
        creator_user: 'Huyền',
        creator_via: 'MM',
        status: 'active',
        status_name: 'Active',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/A1966C6EC5EF67F9DA140BE37783326A-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/61B4A64BE663682E8CB037D9719AD8CD-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/61B4A64BE663682E8CB037D9719AD8CD-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/A1966C6EC5EF67F9DA140BE37783326A.jpg',
            agency_id: 100010,
            agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
        ],
        province: {
            id: '10',
            name: 'Tỉnh Lào Cai',
        },
        district: {
            id: '083',
            name: 'Huyện Mường Khương',
        },
        commune: {
            id: '02758',
            name: 'Xã Tung Chung Phố',
        },desc: 'a'
    },
    {
        merchant_id: 100846,
        merchant_biz_name: 'Merchant Test 06',
        merchant_code: 'MC100846',
        merchant_name: 'Merchant Test 06',
        is_master_merchant: 0,
        master_id: null,
        master_name: null,
        agent_phone: '0912111111',
        agent_email: 'eha80954@eoopy.com',
        agent_identity: '111111111',
        agent_name: 'Huyền',
        company_type: 'CTCP',
        business_type: 4899,
        business_type_name: 'Cable and other pay television (previously Cable Services)',
        tax_code: null,
        address: 'HN',
        created_date: '30/06/2020',
        website: null,
        creator_id: 24,
        creator_user: 'HuyenPTT',
        creator_via: 'MM',
        status: 'active',
        status_name: 'Active',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/6FE48FD20F1A9E0964998EA08C051F7A-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/4B04A686B0AD13DCE35FA99FA4161C65-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/4B04A686B0AD13DCE35FA99FA4161C65-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/6FE48FD20F1A9E0964998EA08C051F7A.jpg',
            agency_id: 100010,
            agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
        ],
        province: {
            id: '08',
            name: 'Tỉnh Tuyên Quang',
        },
        district: {
            id: '074',
            name: 'Huyện Hàm Yên',
        },
        commune: {
            id: '02386',
            name: 'Xã Yên Lâm',
        },desc: 'a'
    },
    {
        merchant_id: 100845,
        merchant_biz_name: 'Merchant Test 04',
        merchant_code: 'MC100845',
        merchant_name: 'Merchant Test 05',
        is_master_merchant: 0,
        master_id: null,
        master_name: null,
        agent_phone: '0911111111',
        agent_email: 'pir51077@eoopy.com',
        agent_identity: '111111111',
        agent_name: 'Huyền',
        company_type: 'DNTN',
        business_type: 4899,
        business_type_name: 'Cable and other pay television (previously Cable Services)',
        tax_code: null,
        address: 'HN',
        created_date: '30/06/2020',
        website: null,
        creator_id: 24,
        creator_user: 'HuyenPTT',
        creator_via: 'MM',
        status: 'active',
        status_name: 'Active',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/AF7C7210EE416AC97ED1058624B8E5D9-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/FC8001F834F6A5F0561080D134D53D29-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/FC8001F834F6A5F0561080D134D53D29-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/AF7C7210EE416AC97ED1058624B8E5D9.jpg',
            agency_id: 100010,
            agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
        ],
        province: {
            id: '08',
            name: 'Tỉnh Tuyên Quang',
        },
        district: {
            id: '072',
            name: 'Huyện Nà Hang',
        },
        commune: {
            id: '02230',
            name: 'Xã Thượng Giáp',
        },desc: 'a'
    },
    {
        merchant_id: 100843,
        merchant_biz_name: 'TRE',
        merchant_code: 'MC100843',
        merchant_name: 'Test Remove Email',
        is_master_merchant: 0,
        master_id: null,
        master_name: null,
        agent_phone: '0948785124',
        agent_email: 'phonglinh123456789@gmail.com',
        agent_identity: '085484841',
        agent_name: 'Ronal Filter',
        company_type: 'DNTN',
        business_type: 4821,
        business_type_name: 'Telegraph services',
        tax_code: '0854545121255',
        address: '70 Long Time Str',
        created_date: '30/06/2020',
        website: 'http://tre-org.org',
        creator_id: 26,
        creator_user: 'Phong Linh SS',
        creator_via: 'MM',
        status: 'wait',
        status_name: 'PendingApproval',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/72C1AADDA502EA552242D4324B36BFC6-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/6E0721B2C6977135B916EF286BCB49EC-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/6E0721B2C6977135B916EF286BCB49EC-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/72C1AADDA502EA552242D4324B36BFC6.jpg',
            agency_id: 100041,
            agency_name: '1234',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 202,
                activated: 1,
            },
            {
                method_id: 82,
                activated: 1,
            },
            {
                method_id: 247,
                activated: 1,
            },
        ],
        province: {
            id: '01',
            name: 'Thành phố Hà Nội',
        },
        district: {
            id: '002',
            name: 'Quận Hoàn Kiếm',
        },
        commune: {
            id: '00040',
            name: 'Phường Đồng Xuân',
        },desc: 'a'
    },
    {
        merchant_id: 100841,
        merchant_biz_name: 'Merchant Test 04',
        merchant_code: 'MC100841',
        merchant_name: 'Merchant Test 04',
        is_master_merchant: 0,
        master_id: null,
        master_name: null,
        agent_phone: '0912222222',
        agent_email: 'ymm23176@eoopy.com',
        agent_identity: '111111111',
        agent_name: 'Huyền',
        company_type: 'CTCP',
        business_type: 4900,
        business_type_name: 'Electric, Gas, Sanitary and Water Utilities',
        tax_code: null,
        address: 'HN',
        created_date: '30/06/2020',
        website: null,
        creator_id: 24,
        creator_user: 'HuyenPTT',
        creator_via: 'MM',
        status: 'reject',
        status_name: 'Rejected',
        additional_infomation: {
            staff_code: null,
            image_shop: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/0E7063BA15ACA69E0C15BE29A4933852-1.jpg',
            ],
            address: null,
            agent_identity_image: [
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/72DA7FD6D1302C0A159F6436D01E9EB0-front.jpg',
                'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/72DA7FD6D1302C0A159F6436D01E9EB0-behind.jpg',
            ],
            bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/0E7063BA15ACA69E0C15BE29A4933852.jpg',
            agency_id: 100010,
            agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
        },
        contract: {
            sign_date: null,
            expire_date: null,
            contract_image: null,
            contract_status: null,
            contract_status_name: null,
            service_status_name: null,
            service_status: null,
        },
        payment_info: {
            settlement_day_display: null,
            settlement_day: null,
            holder_name: null,
            pan: null,
            bank_bin: null,
            bank_name: null,
        },
        payment_method: [
            {
                method_id: 182,
                activated: 1,
            },
        ],
        province: {
            id: '08',
            name: 'Tỉnh Tuyên Quang',
        },
        district: {
            id: '074',
            name: 'Huyện Hàm Yên',
        },
        commune: {
            id: '02383',
            name: 'Xã Minh Khương',
        },desc: 'a'
    },
]
export const MockMerchantStatus = [
    {
        value: 'active',
        desc: 'Active',
    },
    {
        value: 'locked',
        desc: 'Inactive',
    },
    {
        value: 'wait',
        desc: 'PendingApproval',
    },
    {
        value: 'reject',
        desc: 'Rejected',
    },
]
export const MockMerchantAdditionalDetail = {
    additionalInfo: {
        inChargeStaffCode: null,
        agencyInChargeCode: 100010,
        agencyInChargeName: 'Đại lý phát triển Merchant Hoàng Cầu',
        officeImageUrl: [
            'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/9D5868B5CD899FF9DFE300D97F116963-1.jpg',
        ],
        idCardBackImageUrl: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/FC3CF452D3DA8402BEBB765225CE8C0E-behind.jpg',
        idCardFrontImageUrl: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/FC3CF452D3DA8402BEBB765225CE8C0E-front.jpg',
        businessRegNoImageUrl: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/9D5868B5CD899FF9DFE300D97F116963.jpg',
    },
    merchantId: 1001,
};
export const MockMerchantBasicDetail = {
    merchantId: 100901,
    merchantCode: 'MC100901',
    merchantFullName: 'CANIFA',
    merchantShortName: 'CANIFA',
    merchantManageDept: null,
    merchantManageDeptName: null,
    merchantPresenter: 'Huyền',
    merchantPresenterIdNo: '122132122',
    phone: '0912122122',
    email: 'hgxtbcbvb@emlpro.com',
    companyType: 'DNTN',
    companyTypeName: 'merchant.companyType.DNTN',
    businessType: 4899,
    businessTypeName: 'Cable and other pay television (previously Cable Services)',
    businessRegNo: null,
    address: 'HN',
    cityId: '10',
    cityName: 'Tỉnh Lào Cai',
    districtId: '086',
    districtName: 'Huyện Bảo Thắng',
    communeId: '02917',
    communeName: 'Xã Thái Niên',
    website: null,
    status: 'active',
    statusKey: 'merchant.status.Active',
    createDate: '',
};
export const MockMerchantDetail = {
    merchant_id: 100901,
    merchant_biz_name: 'CANIFA',
    merchant_code: 'MC100901',
    merchant_name: 'CANIFA',
    is_master_merchant: 0,
    master_id: null,
    master_name: null,
    agent_phone: '0912122122',
    agent_email: 'hgxtbcbvb@emlpro.com',
    agent_identity: '122132122',
    agent_name: 'Huyền',
    company_type: 'DNTN',
    business_type: 4899,
    business_type_name: 'Cable and other pay television (previously Cable Services)',
    tax_code: null,
    address: 'HN',
    created_date: '06/07/2020',
    website: null,
    creator_id: 24,
    creator_user: 'HuyenPTT',
    creator_via: 'MM',
    status: 'active',
    status_name: 'Active',
    additional_infomation: {
        staff_code: null,
        image_shop: [
            'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/shop-image/9D5868B5CD899FF9DFE300D97F116963-1.jpg',
        ],
        address: null,
        agent_identity_image: [
            'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/FC3CF452D3DA8402BEBB765225CE8C0E-front.jpg',
            'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/agent/FC3CF452D3DA8402BEBB765225CE8C0E-behind.jpg',
        ],
        bsn_registration_cerfiticate: 'http://35.223.25.100:8008/vtl-pg/mm/media/merchant/bsn-certificate/9D5868B5CD899FF9DFE300D97F116963.jpg',
        agency_id: 100010,
        agency_name: 'Đại lý phát triển Merchant Hoàng Cầu',
    },
    contract: {
        sign_date: '07/07/2020',
        expire_date: '31/07/2020',
        contract_image: [
            {
                url: 'http://35.223.25.100:8002/vtl-pg/mm/media/merchant/contract/9D5868B5CD899FF9DFE300D97F116963-0.png',
                name: 'viettelpay.png',
            },
        ],
        contract_status: 1,
        contract_status_name: 'Active',
        service_status_name: 'Active',
        service_status: 1,
    },
    payment_info: {
        settlement_day_display: 'T + 1',
        settlement_day: '1',
        holder_name: 'NGUYEN XUAN LOC',
        pan: '058458443243',
        bank_bin: '970400',
        bank_name: 'Ngân hàng TMCP Sài Gòn Công thương',
    },
    payment_method: [
        {
            method_id: 182,
            activated: 1,
        },
    ],
    province: {
        id: '10',
        name: 'Tỉnh Lào Cai',
    },
    district: {
        id: '086',
        name: 'Huyện Bảo Thắng',
    },
    commune: {
        id: '02917',
        name: 'Xã Thái Niên',
    },
}
export const MockQR = [
    {
        qr_id: '1594024741856788246',
        sub_id: 100901,
        merchant_name: 'CANIFA',
        merchant_code: 'MC100901',
        qr_name: 'QR SP',
        qr_type: 'product',
        qr_url: 'http://35.223.25.100:8003/vtl-pg-qr/view/1594024741856788246',
        status: 'Active',
        des: 'SP123',
        product_code: 'SP123',
        staff_code: null,
        amount: 112000,
        currency: 'VND',
        created_at: '06/07/2020',
    },
]


@Injectable()
export class MockMerchantService extends MerchantService {
    getMerchantLists(request) {
        return of(true);
    }
    checkStaffCode(staffCode: string) {
        return of(true)
    }
    getCompanyType(): Observable<any> {
        return of(true)
    }
    getBusinessType(): Observable<any> {
        return of(true)
    }
    getPaymentMethods(): Observable<any> {
        return of(true);
    }
    public getFileNameFromUrl(url: string) {
        return url && url !== "" ? url.substring(url.lastIndexOf("/") + 1) : "";
    }
}
