// for page title

const baseTitle = "Ví điện tử";

export const TitleConstants = {
  BASE: baseTitle,
  LOGIN: `${baseTitle} | Login`,
  FISRTLOGIN: `${baseTitle} | Change password`,
  DASHBOARD: `${baseTitle} | Home`,
  MANAGE_JOP_POST: `${baseTitle} | Manage job post`,
  PROFILE: `${baseTitle} | Profile`,
  USER: `${baseTitle} | User`,
  REGISTER: `${baseTitle} | Register`,
  FORGOT: `${baseTitle} | Forgot password`,
  DEPARTMENT: `${baseTitle} | Department Management`,
  NOTIFICATION: `${baseTitle} | Notification`,
  TRANSACTION_PAYMENT: `${baseTitle} | Transaction Payment`,
  TRANSACTION_PAYMENT_DETAIL: `${baseTitle} | Transaction Payment Detail`,
  TRANSACTION_REFUND: `${baseTitle} | Transaction Refund`,
  TRANSACTION_REFUND_DETAIL: `${baseTitle} | Transaction Refund Detail`,
  MCC: `${baseTitle} | MCC Management`,
  ISSUER: `${baseTitle} | Issuer Management`,
  FEE: `${baseTitle} | Fee Management`,
  PM: `${baseTitle} | Payment Method Management`,
  ACQUIRER: `${baseTitle} | Acquirer Management`,
  CHANNEL: `${baseTitle} | Channel Management`,
  AGENCY: `${baseTitle} | Agency Management`,
  RISKS_MANAGEMENT_CARD: `${baseTitle} | Card Risk Management`,
  RISKS_MANAGEMENT_BIN: `${baseTitle} | BIN Range Risk Management`,
  RISKS_MANAGEMENT_TRANSACTION: `${baseTitle} | Transaction Risk Management`,
  RISKS_MANAGEMENT_ACCOUNT: `${baseTitle} | Account Risk Management`,
  RISKS_MANAGEMENT_BUSINESS: `${baseTitle} | Business Risk Management`,
  RISKS_MANAGEMENT_IP: `${baseTitle} | IP Risk Management`,
  ROLE_MANAGE: `${baseTitle} | Role Management`,
  REPORT: `${baseTitle} | Report`,
  ERROR: `${baseTitle} | Error 403`,
  STATISTIC: `${baseTitle} | Statistic`,
  MERCHANT: `${baseTitle} | Merchant Management`,
  PAGE_NOT_FOUND: `${baseTitle} | Page Not Found`,
  RECONCILIATION: `${baseTitle} | Reconciliation`,
  MONITORING: `${baseTitle} | Monitoring`,
  TRANSACTION_POS_PAYMENT: `${baseTitle} | Transaction POS Payment`,
  TRANSACTION_POS_REALTIME: `${baseTitle} | Transaction POS Realtime`,
  STATE_BANK_WALLET_BALANCE: `${baseTitle} | Wallet Balance`,
  STATE_BANK_GUARANTEED_BALANCE: `${baseTitle} | Guaranteed Payment Account Balance`,
  STATE_BANK_TYPE_REPORT: `${baseTitle} | Report By Transaction Type`,
  STATE_BANK_TOP_MOST: `${baseTitle} | Top 10 Wallets With The Most Transactions`,
  STATE_BANK_TOP_HIGHEST: `${baseTitle} | Top 10 Wallets With Highest Transaction Value`,
  STATE_BANK_TOP_HIGHEST_DETAIL: `${baseTitle} | Top 10 Wallets With Highest Transaction Value Detail`,
  STATE_BANK_WALLET_VOLATILITY: `${baseTitle} | Month Wallet Volatility`,
};
